<?php

/**
 * Auto generated by MySQL Workbench Schema Exporter.
 * Version 3.0.2 (doctrine2-annotation) on 2016-06-08 15:18:49.
 * Goto https://github.com/johmue/mysql-workbench-schema-exporter for more
 * information.
 */

namespace ErpNET\App\Models\Doctrine\Entities;

use Doctrine\ORM\Mapping as ORM;
use ErpNET\App\Models\Doctrine\CustomTraits\MandanteTrait;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
 *
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 * @ORM\Entity(repositoryClass="SummaryProductContentRepository")
 * @ORM\Table(name="summary_product_contents", indexes={@ORM\Index(name="summary_product_contents_mandante_index", columns={"mandante"}), @ORM\Index(name="summary_product_contents_deleted_at_index", columns={"deleted_at"}), @ORM\Index(name="summary_product_contents_summary_id_index", columns={"summary_id"}), @ORM\Index(name="summary_product_contents_product_id_index", columns={"product_id"})})
 */
class SummaryProductContent extends EntityBase
{
    use MandanteTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    protected $summary_id;

    /**
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    protected $product_id;

    /**
     * @ORM\Column(type="float", precision=8, scale=2)
     */
    protected $stock_quantity;

    /**
     * @ORM\ManyToOne(targetEntity="Summary", inversedBy="summaryProductContents")
     * @ORM\JoinColumn(name="summary_id", referencedColumnName="id", nullable=false)
     */
    protected $summary;

    /**
     * @ORM\ManyToOne(targetEntity="Product", inversedBy="summaryProductContents")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id", nullable=false)
     */
    protected $product;

    public function __construct()
    {
    }

    /**
     * Set the value of id.
     *
     * @param integer $id
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of summary_id.
     *
     * @param integer $summary_id
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setSummaryId($summary_id)
    {
        $this->summary_id = $summary_id;

        return $this;
    }

    /**
     * Get the value of summary_id.
     *
     * @return integer
     */
    public function getSummaryId()
    {
        return $this->summary_id;
    }

    /**
     * Set the value of product_id.
     *
     * @param integer $product_id
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setProductId($product_id)
    {
        $this->product_id = $product_id;

        return $this;
    }

    /**
     * Get the value of product_id.
     *
     * @return integer
     */
    public function getProductId()
    {
        return $this->product_id;
    }

    /**
     * Set the value of stock_quantity.
     *
     * @param float $stock_quantity
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setStockQuantity($stock_quantity)
    {
        $this->stock_quantity = $stock_quantity;

        return $this;
    }

    /**
     * Get the value of stock_quantity.
     *
     * @return float
     */
    public function getStockQuantity()
    {
        return $this->stock_quantity;
    }

    /**
     * Set Summary entity (many to one).
     *
     * @param \ErpNET\App\Models\Doctrine\Entities\Summary $summary
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setSummary(Summary $summary = null)
    {
        $this->summary = $summary;

        return $this;
    }

    /**
     * Get Summary entity (many to one).
     *
     * @return \ErpNET\App\Models\Doctrine\Entities\Summary
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Set Product entity (many to one).
     *
     * @param \ErpNET\App\Models\Doctrine\Entities\Product $product
     * @return \ErpNET\App\Models\Doctrine\Entities\SummaryProductContent
     */
    public function setProduct(Product $product = null)
    {
        $this->product = $product;

        return $this;
    }

    /**
     * Get Product entity (many to one).
     *
     * @return \ErpNET\App\Models\Doctrine\Entities\Product
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function __sleep()
    {
        return array('id', 'created_at', 'updated_at', 'deleted_at', 'summary_id', 'product_id', 'mandante', 'stock_quantity');
    }
}